it:
  code: ita
  name: italiano
  t:
    active_lang: lingua attiva
    follow_us: seguici su
    header_link_pt: Piano Triennale
    header_link_developers: Developers
    header_link_design: Designers
    header_link_forum: Forum
    header_link_docs: Docs
    header_link_github: GitHub
    header_title: Trasformazione Digitale
    footer_address: Indirizzo
    footer_address_sub: ''
    footer_contacts: Contatti
    footer_contacts_sub: ''
    footer_link_privacy_policy: privacy
    footer_link_legal_notes: note legali
    footer_link_credits: crediti
    footer_link_accessibility_statement: Dichiarazione di accessibilità
    footer_title: ''
    institutional_site: Sito istituzionale
    in_collaboration_with: In collaborazione con
    actions_progress: In corso
    actions_from: 'Da '
    actions_to: ' a '
    actions_by: 'Entro '
    actions_at: 'A '
    get_json: Scarica il JSON
    months:
      '01': gennaio
      '02': febbraio
      '03': marzo
      '04': aprile
      '05': maggio
      '06': giugno
      '07': luglio
      '08': agosto
      '09': settembre
      '10': ottobre
      '11': novembre
      '12': dicembre
    lang_on_site: sito in italiano
    navigation_network_menu_label: Menu di navigazione del network
    navigation_menu_label: Menu di navigazione
    navigation_menu_esc: esci dalla navigazione
    scrolltop_label: torna all'inizio dei contenuti
    site_subtitle: "per l'informatica nella Pubblica Amministrazione"
    site_title: Piano Triennale
    site_title_mobile: Piano Triennale ICT
    share_msg: condividi
    skiplink_goto_content: vai ai contenuti
    skiplink_goto_navigation: vai alla navigazione del sito
    toggle_menu_label: accedi al menu
    toggle_network_menu_label: accedi al menu del network
    see_more: per saperne di più
    goto_chapter: vai al capitolo
    goto_chapter_en: read the chapter
    goto_forum: partecipa
    goto_plan-2017: leggi la versione 2017-2019
    deepen: per approfondire
    download_chapter: scarica il capitolo
    discuss: per confrontarti
    cap_on_github: vai al capitolo su github
    by: di
    on_: "su"
    actions: le azioni
    amministrazioni_centrali: amministrazioni centrali
    amministrazioni_territoriali: amministrazioni territoriali
    tempi: tempi
    attori: attori
    descrizione: descrizione
    risultati: risultati
    aree-intervento: aree di intervento
    stato: stato
    completata: completata
    completo: completo
    in_corso: in corso
    bloccato: bloccato
    home_hero: |
      «Lorem ipsum dolor sit amet, consectetur adipiscing elit.
      Etiam vehicula neque eu lectus congue dapibus. Nullam ex massa, congue sit amet turpis id, cursus eleifend eros.»
    home_hero_mobile: |
      «Lorem ipsum dolor sit amet, consectetur adipiscing elit.
      Etiam vehicula neque eu lectus congue dapibus. Nullam ex massa, congue sit amet turpis id, cursus eleifend eros.»
    home_tools_title: Strumenti
    home_tools_subtitle: Ci appoggiamo a strumenti già esistenti e molto conosciuti per fornirti le informazioni, il codice e il supporto di cui hai bisogno
    home_header_button_text: vai al piano
    home_pt_title: Cos'è il Piano Triennale
    home_pt_description: |
      Il Piano Triennale per l'informatica nella Pubblica Amministrazione 2024-2026 indica le linee di azione per promuovere la trasformazione digitale del settore pubblico e del Paese.
      
      Il nuovo Piano presenta, rispetto alle precedenti edizioni, dei cambiamenti nella sua struttura e approfondisce alcuni contenuti per sostenere in modo efficace le pubbliche amministrazioni nel processo di implementazione e gestione dei servizi digitali.
      
      Per la prima volta il Piano affronta approfonditamente anche il tema dell'Intelligenza Artificiale, fornendo indicazioni e principi generali che dovranno essere adottati dalle amministrazioni e declinati in fase di applicazione, tenendo in considerazione lo scenario in rapida evoluzione.
      
      Il Piano triennale 2024-2026 è il risultato di un'attività di scambio e collaborazione tra amministrazioni e soggetti istituzionali che hanno preso parte ad un Tavolo di concertazione, con l'obiettivo di costituire una struttura permanente per un'azione continua di definizione dei contenuti e delle strategie indicate dal Piano stesso.
      
      La strategia alla base del Piano triennale 2024-2026 nasce dalla necessità di ripensare alla programmazione della digitalizzazione delle pubbliche amministrazioni basata su nuove leve strategiche, tenendo conto di tutti gli attori coinvolti nella trasformazione digitale del Paese e degli obiettivi fissati per il 2030 dal percorso tracciato dalla Commissione europea per il Decennio Digitale.
    home_pt_howto_title: Consulta il Piano
    home_pt_howto:
      # - text: |
      #    Nelle pagine di questo sito vengono riassunti i contenuti del Piano Triennale, suddivisi per [capitoli](/piano) e [azioni](/azioni).
      #    Il documento completo è disponibile online in versione navigabile ottimizzata per dispositivi mobili o in PDF.
      - text: |
          Il documento completo è disponibile online in versione navigabile ottimizzata per dispositivi mobili o in PDF.
        links:
          - type: button
            icon: read
            label: Versione navigabile
            href: 'https://docs.italia.it/italia/piano-triennale-ict/pianotriennale-ict-doc/'
            target_blank: true
          - icon: download-alt
            label: scarica il pdf
            href: 'https://www.agid.gov.it/sites/default/files/repository_files/piano_triennale_per_linformatica_nella_pa_2024-2026.pdf'
            target_blank: true
    home_pt_dpcm_download_title: DPCM 12 gennaio 2024
    home_pt_dpcm_download:
      - text: |
          Approvazione Piano Triennale per l'informatica nella Pubblica Amministrazione 2024-2026
        links:
          - icon: download-alt
            label: scarica il pdf
            href: '/assets/pdf/2024-2026/DPCM_12_gennaio_2024.pdf'
            target_blank: true
    home_links:
      plan: /piano
    quotes:
      2024:
        butti:
          text: |
            Il nuovo Piano Triennale per l'informatica nella Pubblica Amministrazione rappresenta un passo cruciale verso la trasformazione digitale del nostro Paese.
            È uno strumento strategico che guida l'evoluzione digitale della PA, definendo obiettivi chiari e risultati attesi.
            Il Piano si focalizza sull'efficacia dell'azione amministrativa, garantendo che ogni aspetto della digitalizzazione sia orientato al miglioramento dei servizi pubblici e alla realizzazione di un sistema più efficiente e accessibile per tutti i cittadini.
          author_name: Alessio Butti
          author_role: |
            Sottosegretario alla Presidenza del Consiglio
            con delega all'innovazione tecnologica
      2020:
        pisano:
          text: |
            Ringrazio l'Agenzia per l'Italia digitale e il Dipartimento per la Trasformazione digitale per la stesura del piano. Entrambi - insieme alle amministrazioni centrali e locali - avranno un ruolo operativo in tutte le aree del piano: dal miglioramento della capacità di generare ed erogare nuovi servizi, all'evoluzione di quelli esistenti fino alla migrazione dei servizi su infrastrutture sicure, efficienti e sostenibili.<br>
            I nostri prossimi obiettivi hanno scadenza 28/02/2021 e vedranno tutti noi  impegnati  a promuovere l'utilizzo di SPID (Sistema Pubblico di Identità Digitale) e CIE (Carta d'Identità elettronica) come le sole credenziali di accesso ai servizi digitali della Pubblica amministrazione, la piattaforma pagoPa come sistema di pagamento elettronico e l'avvio  dei processi di digitalizzazione per erogare tutti i servizi al cittadino attraverso l'applicazione 'IO'
          text_short: |
            Ringrazio l'Agenzia per l'Italia digitale e il Dipartimento per la Trasformazione digitale per la stesura del piano. Entrambi - insieme alle amministrazioni centrali e locali - avranno un ruolo operativo in tutte le aree del piano: dal miglioramento della capacità di generare ed erogare nuovi servizi, all'evoluzione di quelli esistenti fino alla migrazione dei servizi su infrastrutture sicure, efficienti e sostenibili.
          author_name: Paola Pisano
          author_role: Ministra per l'Innovazione Tecnologica e la Digitalizzazione
      2019:
        dedica:
          text: |
            Questo Piano Triennale è dedicato ad Antonella Giulia Pizzaleo, innovatrice paziente e geniale della Pubblica Amministrazione, che su più tavoli ha rappresentato la Regione Lazio nei molti confronti durante il lavoro di redazione di questo Piano stesso e che ha fattivamente contribuito con i suoi suggerimenti e con le sue garbate osservazioni.
            Con la nostra gratitudine per aver garantito, con costante impegno ed approccio propositivo, un impulso forte ed innovativo alla digitalizzazione della PA a livello territoriale e nazionale.
        bongiorno:
          text: |
            «Con il nuovo Piano Triennale si gettano le basi per consentire al settore pubblico di cominciare a correre e recuperare terreno nel percorso appena avviato verso una trasformazione digitale concreta e inclusiva. Un percorso non facile ma ragionevole e concreto, che fa perno sul Responsabile per la transizione al digitale e vede imprese e cittadini protagonisti di un progetto di crescita digitale del Paese.»
          text_short: |
            «Con il nuovo Piano Triennale si gettano le basi per consentire al settore pubblico di cominciare a correre e recuperare terreno nel percorso appena avviato verso una trasformazione digitale concreta e inclusiva. Un percorso non facile ma ragionevole e concreto, che fa perno sul Responsabile per la transizione al digitale e vede imprese e cittadini protagonisti di un progetto di crescita digitale del Paese.»
          author_name: Giulia Bongiorno
          author_role: Ministro per la Pubblica Amministrazione
      2017:
        gentiloni:
          text: |
            «La trasformazione digitale è una priorità del Governo. Il Piano Triennale richiede un gioco di squadra per semplificare la Pubblica Amministrazione e la vita dei cittadini»
          text_short: |
            «La trasformazione digitale è una priorità del Governo. Il Piano Triennale richiede un gioco di squadra per semplificare la Pubblica Amministrazione e la vita dei cittadini»
          author_name: Paolo Gentiloni
          author_role: Presidente del Consiglio dei Ministri
        madia:
          text: |
            «Con il Piano Triennale prosegue la trasformazione digitale che permetterà alle pubbliche amministrazioni di diventare più efficienti e mettere il cittadino al centro delle loro azioni. L'aggiornamento del Codice dell'Amministrazione Digitale sarà un ulteriore passo per liberare l'innovazione dai troppi regolamenti e rafforzare i diritti di cittadinanza digitale»
          text_short: |
            «Con il Piano Triennale prosegue la trasformazione digitale che permetterà alle pubbliche amministrazioni di diventare più efficienti e mettere il cittadino al centro delle loro azioni. L'aggiornamento del Codice dell'Amministrazione Digitale sarà un ulteriore passo per liberare l'innovazione dai troppi regolamenti e rafforzare i diritti di cittadinanza digitale»
          author_name: Marianna Madia
          author_role: Ministro per la semplificazione e la Pubblica Amministrazione
        piacentini:
          text: |
            «Stiamo introducendo una modalità di partecipazione completamente nuova, certi che per raggiungere l'obiettivo della trasformazione digitale dei servizi della Pubblica Amministrazione si debba agire in maniera collaborativa»
          text_short: |
            «Stiamo introducendo una modalità di partecipazione completamente nuova, certi che per raggiungere l'obiettivo della trasformazione digitale dei servizi della Pubblica Amministrazione si debba agire in maniera collaborativa»
          author_name: Diego Piacentini
          author_role: Commissario straordinario per l'attuazione dell'Agenda Digitale
          goto_link: 'https://medium.com/@diegopia/piano-triennale-trasformazione-digitale-pubblica-amministrazione-linee-guida-design-sviluppo-open-source-a54e27d55be9'
          goto_label: Leggi il post completo su Medium
    capitoli_title: Tutti i capitoli del piano
    capitoli:
      piano-triennale: Piano Triennale
      contesto-normativo: Contesto normativo
      infrastrutture: Infrastrutture
      modello-di-interoperabilita: Modello di interoperabilità
      dati-della-pa: Dati della Pubblica Amministrazione
      piattaforme: Piattaforme
      ecosistemi: Ecosistemi
      sicurezza-informatica: Sicurezza informatica
      servizi-digitali: Strumenti per la generazione e la diffusione di servizi digitali
      modelli-e-strumenti-innovazione: Modelli e strumenti per l'innovazione
      governare-la-trasformazione-digitale: Governare la trasformazione digitale
      razionalizzazione-della-spesa: Razionalizzazione della spesa
      indicazioni-per-le-pa: Indicazioni per le pubbliche amministrazioni
    temi_title: I capitoli
    modello_intro: Clicca sulla sezione che ti interessa.
    partecipa: Partecipa
    forum_intro: "Chiunque può partecipare al forum di discussione e contribuire alla diffusione e all'implementazione del Piano Triennale."
    temi:
      servizi-digitali: 
        name: Servizi digitali
        ref: servizi-digitali
      modelli-e-strumenti-innovazione:
        name: Modelli e strumenti per l'innovazione
        ref: modelli-e-strumenti-innovazione
      ecosistemi: 
        name: Ecosistemi
        ref: ecosistemi
      piattaforme:
        name: Piattaforme
        ref: piattaforme
      dati-della-pa: 
        name: Dati della PA
        ref: dati-della-pa
      modello-di-interoperabilita: 
        name: Modello di interoperabilità
        ref: modello-di-interoperabilita
      infrastrutture: 
        name: Infrastrutture
        ref: infrastrutture
      governare-la-trasformazione-digitale:
        name: Governare la trasformazione digitale
        ref: governare-la-trasformazione-digitale
      sicurezza: 
        name: Sicurezza
        ref: sicurezza
      pdnd:
        name: Piattaforma Digitale Nazionale Dati
        ref: dati-della-pa
    gov_full: Presidenza del Consiglio dei Ministri
    gov_link: http://www.governo.it
    gov_logo: /assets/images/governo.svg
    gov_logo_alt: /assets/images/governo-alt.svg
    dfp_full: Dipartimento della funzione pubblica
    dfp_link: http://www.funzionepubblica.gov.it
    dfp_logo: /assets/images/governo.svg
    dfp_logo_alt: /assets/images/governo-alt.svg
    owner_short: AGID
    owner_full: Agenzia per l'Italia Digitale
    owner_link: https://www.agid.gov.it
    owner_logo: /assets/images/agid-logo.svg
    owner_logo_alt: /assets/images/agid-logo-alt.svg
    partner_short: DTD
    partner_full: Dipartimento per la trasformazione digitale
    partner_link: https://innovazione.gov.it/
    privacy_link: https://developers.italia.it/it/privacy-policy
    partner_logo: /assets/images/logo-dtd-white.svg
    partner_logo_alt: /assets/images/logo-dtd-white-alt.svg

en:
  code: eng
  name: english
  t:
    
